FROM openjdk:8-slim as build
ARG maildrop_ver=master

RUN apt update && \
    apt install -y curl zip && \
    curl -L https://piccolo.link/sbt-1.1.5.tgz | tar xzf -
COPY maildrop /maildrop
RUN cd /maildrop/web && \
    ./activator dist && \
    unzip -d dist target/universal/web-2.0.zip

FROM openjdk:8-slim
COPY --from=build --chown=daemon /maildrop/web/dist/web-2.0 /maildrop/web
USER daemon
COPY startup.sh /startup.sh

ENTRYPOINT ["/startup.sh", "web", "@*"]
