FROM openjdk:8-slim as build
ARG maildrop_ver=master

RUN apt update && \
    apt install -y curl zip && \
    curl -L https://piccolo.link/sbt-1.1.5.tgz | tar xzf -
COPY maildrop /maildrop
RUN cd /maildrop/web && \
    /sbt/bin/sbt universal:packageZipTarball && \
    mkdir dist && \
    tar xzvf target/universal/web-2.0.tgz -C dist --strip 1

FROM openjdk:8-slim
COPY --from=build --chown=daemon /maildrop/web/dist /maildrop/web
USER daemon
COPY startup.sh /startup.sh

ENTRYPOINT ["/startup.sh", "web", "$*"]
