FROM openjdk:8-slim as build

ADD https://piccolo.link/sbt-1.2.3.tgz /tmp
RUN tar xzvf /tmp/sbt-1.2.3.tgz -C /
COPY maildrop /maildrop
RUN cd /maildrop/web && \
    /sbt/bin/sbt universal:packageZipTarball && \
    tar xzvf target/universal/web-2.0.tgz

FROM openjdk:8-slim
COPY --from=build --chown=daemon /maildrop/web/web-2.0 /maildrop/web
USER daemon
COPY startup.sh /startup.sh

ENTRYPOINT ["/startup.sh"]
CMD ["web", "$@"]
